### ISSUE TITLE
Торговля

### ISSUE THREAD

**Issue by Archemagus** [animusdev/BlueTorchAdmiralty#21]
У торгашей есть на станции специальный телепортационый пад и рядом компьютер для торговли. Так вот. Ничего нельзя продать. Абсолютно! Даже если торговец пишет, что нуждается в этом предмете, он отказывается его покупать. Как то так. По этому нельзя менять довольно классные шняги у воксов

**Comment by n0rm4ld3f4ult** [comment]
Архимаг, об этом уже сообщил кое-кто ранее, читай подробнее.
