### ISSUE TITLE
Энергия в хирургии роботехников

### ISSUE THREAD

**Issue by Ahmedok** [animusdev/BlueTorchAdmiralty#9]
Очевидно на карте отсутствует кусок проводки, который питает эту самую хирургию. #11

**Comment by SS13Course** [comment]
Пофикшено беевцами, нужен мердж.

**Comment by Ahmedok** [comment]
Не знаю ничего про бейцов, но я только что это сам зафиксил

**Comment by Ahmedok** [comment]
Смержено и пофикшено, ура.
